/**
 * cleaners/news-generic.js
 * Generic cleaner for news sites
 * Targets: "Ask AI" panels, AI summary widgets, "AI-generated" disclosure badges
 */

const NewsGenericCleaner = {
  // Common patterns across news sites
  selectors: [
    // "Ask AI" / "AI Chat" widgets (usually in sidebar)
    '[aria-label*="Ask AI"]',
    '[aria-label*="Ask a question"]',
    '[class*="ai-widget"]',
    '[class*="ask-ai"]',
    '[class*="ai-chat"]',
    
    // AI summary / explainer sections
    '[class*="ai-summary"]',
    '[class*="ai-explainer"]',
    '[data-component="ai-summary"]',
    
    // "Generated by AI" or "AI-assisted" badges
    '[class*="ai-generated"]',
    '[data-ai-generated]',
    '[aria-label*="AI-generated"]',
    '[aria-label*="AI-assisted"]',
  ],

  /**
   * Detect if container is an AI feature widget
   */
  isAIWidget(el) {
    const text = (el.innerText || '').toLowerCase();
    const classStr = (el.className || '').toLowerCase();
    const id = (el.id || '').toLowerCase();
    
    const aiMarkers = /ask ai|ai chat|ai summary|ai explainer|generated by ai|ai-assisted|ask a question.*ai/;
    
    return aiMarkers.test(text) || 
           aiMarkers.test(classStr) || 
           aiMarkers.test(id);
  },

  /**
   * Hide AI summary widgets and AI badges
   */
  clean(aiKeywords, containsAnyFunc, hideFunc) {
    const toHide = [];

    // Strategy 1: Direct selector match (explicit AI widgets)
    this.selectors.forEach(sel => {
      try {
        document.querySelectorAll(sel).forEach(el => {
          if (hideFunc(el)) {
            toHide.push(el);
          }
        });
      } catch (e) {
        // Selector error, skip
      }
    });

    // Strategy 2: Heuristic - look for sidebars/widgets with "Ask AI" text
    const commonWidgetContainers = document.querySelectorAll('aside, [role="complementary"], [class*="sidebar"], [class*="widget"]');
    commonWidgetContainers.forEach(widget => {
      if (this.isAIWidget(widget) && hideFunc(widget)) {
        toHide.push(widget);
      }
    });

    // Strategy 3: Hide disclosure badges ("AI-generated", "AI-assisted")
    document.querySelectorAll('[class*="badge"], [class*="label"], [class*="tag"]').forEach(badge => {
      const text = (badge.innerText || '').toLowerCase();
      if (/ai.generated|ai.assisted|generated by ai/i.test(text)) {
        if (hideFunc(badge)) {
          toHide.push(badge);
        }
      }
    });

    return toHide.length;
  },

  /**
   * Observer for dynamic news content
   */
  observe(observer, scanFunc) {
    // News sites often use infinite scroll or lazy loading
    observer.observe(document.body, { 
      childList: true, 
      subtree: true 
    });
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = NewsGenericCleaner;
}
