/**
 * content-enhanced.js
 * Enhanced content script integrating site-specific cleaners
 * Replaces content.js with support for modular site-specific logic
 */

const STOP_WORDS_MIN_LEN = 2;
const HIDDEN_CLASS = "noai-hidden-block";
const BEHAVIORAL_SCORE_THRESHOLD = 5;
const AI_BADGE_PATTERNS = [
  /powered by ai/i,
  /ai overview/i,
  /ask ai/i,
  /generated by ai/i,
  /ai summary/i,
  /ai answer/i,
  /gemini|bard|copilot|chatgpt|claude|midjourney|stable diffusion/i
];
const ANIMATION_CLASS_HINTS = ["typing", "typewriter", "shimmer", "skeleton", "marquee"];

const PLATFORM_MARKERS = [
  { name: "GoogleCleaner", selector: '[data-sokoban-container][data-answer-type]' },
  { name: "FacebookCleaner", selector: '[data-testid="feed_story_wrapper"]' },
  { name: "YouTubeCleaner", selector: "ytd-rich-item-renderer, ytd-two-column-browse-results-renderer" },
  { name: "NewsGenericCleaner", selector: '[aria-label*="Ask AI"], [class*="ai-summary"], [class*="ai-generated"]' }
];

const GENERIC_SCAN_EXCLUSIONS = [
  "youtube.com",
  "www.youtube.com",
  "m.youtube.com",
  "music.youtube.com"
];

function norm(s) {
  return (s || "").toLowerCase().trim();
}

function escapeRegExp(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function containsAny(haystack, needles) {
  const source = haystack || "";
  const normalizedHaystack = norm(source);

  for (const n of needles) {
    const normalizedNeedle = norm(n);
    if (normalizedNeedle.length < STOP_WORDS_MIN_LEN) continue;

    if (normalizedNeedle.length <= 3) {
      const regex = new RegExp(`\\b${escapeRegExp(normalizedNeedle)}\\b`, "i");
      if (regex.test(source)) return true;
    } else if (normalizedHaystack.includes(normalizedNeedle)) {
      return true;
    }
  }

  return false;
}

function isProbablyAdContainer(el, adPhrases) {
  const aria = el.getAttribute?.("aria-label") || "";
  const role = el.getAttribute?.("role") || "";
  const idc = `${el.id || ""} ${el.className || ""}`;

  if (containsAny(aria, adPhrases)) return true;
  if (containsAny(role, ["banner", "complementary"])) return true;
  if (containsAny(idc, ["ad", "ads", "sponsor", "promoted", "promotion"])) return true;

  const text = el.innerText || "";
  if (containsAny(text, adPhrases)) return true;

  return false;
}

function hide(el) {
  if (!el || el.nodeType !== 1) return false;
  if (el.dataset?.noaiHidden === "1") return false;
  el.dataset.noaiHidden = "1";
  el.classList.add(HIDDEN_CLASS);
  el.style.setProperty("display", "none", "important");
  return true;
}

function showAllHidden() {
  const hiddenNodes = document.querySelectorAll('[data-noai-hidden="1"]');
  hiddenNodes.forEach((node) => {
    node.style.removeProperty("display");
    node.dataset.noaiHidden = "0";
  });
  chrome.runtime
    .sendMessage({ type: "noai:reset" })
    .catch(() => {});
}

function scoreNodeForAI(el, aiKeywords) {
  if (!el) return 0;
  let score = 0;
  const text = (el.innerText || "").toLowerCase();
  const classStr = (el.className || "").toLowerCase();

  if (containsAny(text, aiKeywords)) score += 2;
  if (AI_BADGE_PATTERNS.some((regex) => regex.test(text))) score += 3;
  if (AI_BADGE_PATTERNS.some((regex) => regex.test(classStr))) score += 2;

  const hasAnimationHint = ANIMATION_CLASS_HINTS.some((hint) => classStr.includes(hint));
  if (hasAnimationHint) score += 1;

  if (el.querySelector?.("[data-ai], [data-ai-generated], [aria-label*='AI']")) score += 3;
  if (el.querySelector?.("svg use[href*='sparkle'], svg use[href*='star']")) score += 1;

  const role = (el.getAttribute?.("role") || "").toLowerCase();
  if (["complementary", "region"].includes(role)) score += 1;

  if (el.querySelector?.("button, [role='button']") && AI_BADGE_PATTERNS.some((regex) => regex.test(text))) {
    score += 1;
  }

  return score;
}

function tryLoadCleanerByMarker(node) {
  if (!node?.querySelectorAll) return null;
  for (const marker of PLATFORM_MARKERS) {
    if (node.matches?.(marker.selector) || node.querySelector(marker.selector)) {
      return marker.name;
    }
  }
  return null;
}

/**
 * Load and integrate site-specific cleaner based on hostname
 */
async function loadSiteSpecificCleaner(host) {
  const googleTlds = [
    "com",
    "co.uk",
    "co.jp",
    "co.in",
    "com.au",
    "ca",
    "de",
    "fr",
    "es",
    "it",
    "in",
    "br",
    "mx"
  ];

  const newsHosts = [
    "bbc.com",
    "bbc.co.uk",
    "cnn.com",
    "nytimes.com",
    "theguardian.com",
    "washingtonpost.com",
    "reuters.com",
    "apnews.com",
    "wsj.com"
  ];

  if (googleTlds.some((tld) => host === `google.${tld}` || host.endsWith(`.google.${tld}`) || host.endsWith(`google.${tld}`))) {
    return "GoogleCleaner";
  }

  if (host.includes("google.") || host.endsWith(".google.com")) return "GoogleCleaner";
  if (host.includes("facebook.com") || host.includes("messenger.com")) return "FacebookCleaner";
  if (host.includes("youtube.com")) return "YouTubeCleaner";
  if (newsHosts.some((domain) => host === domain || host.endsWith(`.${domain}`))) {
    return "NewsGenericCleaner";
  }

  return null;
}

/**
 * Generic DOM scanning (works across all sites)
 */
function scanNodeGeneric(node, aiKeywords, disclosurePhrases, adPhrases, notifyDetection) {
  if (!node || node.nodeType !== 1) return 0;
  const el = /** @type {Element} */ (node);

  let hidden = 0;

  // 1) Hide disclosure blocks (AI-generated labels, etc.)
  const txt = el.innerText || "";
  if (containsAny(txt, disclosurePhrases)) {
    if (hide(el)) {
      hidden++;
      chrome.runtime.sendMessage({ type: "noai:hidden-inc" }).catch(() => {});
      notifyDetection?.("disclosure", txt.slice(0, 80));
    }
    return hidden; // Don't process children
  }

  // 2) Hide AI-themed ads: (ad container) AND (AI keyword)
  const container = el.closest?.("article, section, div, li") || el;
  if (isProbablyAdContainer(container, adPhrases) && containsAny(container.innerText || "", aiKeywords)) {
    if (hide(container)) {
      hidden++;
      chrome.runtime.sendMessage({ type: "noai:hidden-inc" }).catch(() => {});
      notifyDetection?.("sponsored-ai", container.innerText.slice(0, 80));
    }
    return hidden;
  }

  // 3) Behavioral heuristics fallback
  const score = scoreNodeForAI(el, aiKeywords);
  if (score >= BEHAVIORAL_SCORE_THRESHOLD) {
    if (hide(el)) {
      hidden++;
      chrome.runtime.sendMessage({ type: "noai:hidden-inc" }).catch(() => {});
      notifyDetection?.("behavioral", `${score}`);
    }
    return hidden;
  }

  return hidden;
}

(async function main() {
  const host = location.hostname;
  const skipGenericScan = GENERIC_SCAN_EXCLUSIONS.some((domain) => host === domain || host.endsWith(`.${domain}`));

  const {
    enabled,
    aiKeywords,
    disclosurePhrases,
    adPhrases,
    disabledHosts,
    perSiteEnabled
  } = await chrome.storage.sync.get([
    "enabled",
    "aiKeywords",
    "disclosurePhrases",
    "adPhrases",
    "disabledHosts",
    "perSiteEnabled"
  ]);

  if (!enabled) return;
  if ((disabledHosts || []).includes(host)) return;
  if (perSiteEnabled && perSiteEnabled[host] === false) return;

  chrome.runtime.sendMessage({ type: "noai:reset" }).catch(() => {});

  // Inject generic CSS
  const style = document.createElement("style");
  style.textContent = `
    [data-ai], .ai-generated, .ai-content, .generated-by-ai { display:none !important; }
    .${HIDDEN_CLASS} { display:none !important; }
  `;
  document.documentElement.appendChild(style);

  // Try to load and execute site-specific cleaner
  const cleanerName = await loadSiteSpecificCleaner(host);
  let siteSpecificCleaner = null;
  let detectedCleaner = cleanerName;

  if (detectedCleaner) {
    // Check if cleaner exists in global scope (loaded via separate script)
    if (typeof window[detectedCleaner] !== "undefined") {
      siteSpecificCleaner = window[detectedCleaner];
    }
  }

  const detectionNotified = new Set();
  function notifyDetection(reason, meta) {
    const key = `${reason}`;
    if (detectionNotified.has(key)) return;
    detectionNotified.add(key);
    chrome.runtime
      .sendMessage({ type: "noai:ai-panel-observed", host, reason, meta })
      .catch(() => {});
  }

  function maybeActivateCleanerFromNode(node) {
    if (siteSpecificCleaner) return;
    const found = tryLoadCleanerByMarker(node);
    if (found && typeof window[found] !== "undefined") {
      siteSpecificCleaner = window[found];
      detectedCleaner = found;
    }
  }

  // Main scanning function
  function scanNode(node) {
    let hiddenCount = 0;
    if (!skipGenericScan) {
      hiddenCount = scanNodeGeneric(node, aiKeywords, disclosurePhrases, adPhrases, notifyDetection);
    }

    // If site-specific cleaner exists, also run it
    if (siteSpecificCleaner && siteSpecificCleaner.clean) {
      const siteCount = siteSpecificCleaner.clean(aiKeywords, containsAny, hide);
      if (siteCount > 0) {
        chrome.runtime.sendMessage({ type: "noai:hidden-inc", amount: siteCount }).catch(() => {});
      }
    }

    return hiddenCount;
  }

  // Initial scan
  document.querySelectorAll("article, section, div, li").forEach(scanNode);

  // Mutation observer for dynamic content
  const obs = new MutationObserver((mutations) => {
    for (const m of mutations) {
      for (const n of m.addedNodes) {
        maybeActivateCleanerFromNode(n);
        scanNode(n);
        if (n?.querySelectorAll) {
          n.querySelectorAll("article, section, div, li").forEach(scanNode);
        }
      }
    }
  });

  obs.observe(document.documentElement, { childList: true, subtree: true });

  chrome.runtime.onMessage.addListener((msg) => {
    if (msg?.type === "noai:show-hidden") {
      showAllHidden();
    }
  });
})();
