/**
 * sw-enhanced.js
 * Enhanced service worker with DNR manager integration
 * Replaces sw.js with DNR dynamic rule management
 */

// Import DNR manager logic (embedded here for simplicity)
const DNR_RULE_ID_PREFIX = 10000;

function parseDomainsToDNRRules(domainListText) {
  const domains = domainListText
    .split("\n")
    .map(line => line.trim())
    .filter(line => line && !line.startsWith("#"));

  return domains.map((domain, idx) => ({
    id: DNR_RULE_ID_PREFIX + idx,
    priority: 1,
    action: { type: "block" },
    condition: {
      urlFilter: `||${domain}^`,
      resourceTypes: ["main_frame", "sub_frame", "xmlhttprequest", "image", "stylesheet", "font"]
    }
  }));
}

async function updateDNRRulesFromStorage() {
  try {
    const { dnrDomainList = "" } = await chrome.storage.sync.get(["dnrDomainList"]);

    if (!dnrDomainList.trim()) {
      console.log("[DNR Manager] No domain list configured.");
      return;
    }

    const rules = parseDomainsToDNRRules(dnrDomainList);
    const existingRules = await chrome.declarativeNetRequest.getDynamicRules();
    const existingIds = existingRules.map(r => r.id);

    await chrome.declarativeNetRequest.updateDynamicRules({
      removeRuleIds: existingIds,
      addRules: rules
    });

    console.log(`[DNR Manager] Updated ${rules.length} dynamic rules.`);
  } catch (err) {
    console.error("[DNR Manager] Error:", err);
  }
}

// ============================================
// Default configuration
// ============================================

const DEFAULTS = {
  enabled: true,
  aiKeywords: [
    "ai", "artificial intelligence", "chatgpt", "gpt", "copilot", "prompt",
    "llm", "generative", "midjourney", "stable diffusion", "claude", "gemini"
  ],
  disclosurePhrases: [
    "ai-generated", "generated by ai", "written by ai", "created with ai",
    "ai-assisted", "ai-powered"
  ],
  adPhrases: ["sponsored", "promoted", "ad", "paid partnership", "advertisement"],
  disabledHosts: [],
  perSiteEnabled: {},
  dnrDomainList: `# Known AI content farms
writesonic.com
copy.ai
jasper.ai
rytr.me
anyword.com
essaybot.com
smodin.io
spinbot.com
paraphrasebot.com
quillbot.com
contentstudio.io
` // Users can add more in options
};

const hiddenCountByTab = new Map();

// ============================================
// Extension lifecycle
// ============================================

chrome.runtime.onInstalled.addListener(async () => {
  console.log("[NoAI Slop Cleaner] Extension installed/updated.");
  
  // Initialize default settings
  const existing = await chrome.storage.sync.get(Object.keys(DEFAULTS));
  const toSet = {};
  for (const [k, v] of Object.entries(DEFAULTS)) {
    if (existing[k] === undefined) {
      toSet[k] = v;
    }
  }
  
  if (Object.keys(toSet).length) {
    await chrome.storage.sync.set(toSet);
    console.log("[NoAI] Defaults initialized.");
  }

  // Initialize DNR rules
  await updateDNRRulesFromStorage();
});

// ============================================
// Message handling
// ============================================

chrome.runtime.onMessage.addListener((msg, sender) => {
  if (!sender.tab?.id) return;
  const tabId = sender.tab.id;

  if (msg?.type === "noai:hidden-inc") {
    const next = (hiddenCountByTab.get(tabId) || 0) + (msg.amount || 1);
    hiddenCountByTab.set(tabId, next);
    chrome.action.setBadgeText({ tabId, text: String(next) });
    chrome.action.setBadgeBackgroundColor({ tabId, color: "#444" });
  }

  if (msg?.type === "noai:reset") {
    hiddenCountByTab.set(tabId, 0);
    chrome.action.setBadgeText({ tabId, text: "" });
  }

  // Handle DNR domain list updates
  if (msg?.type === "noai:dnr-update") {
    updateDNRRulesFromStorage();
  }
});

// ============================================
// Cleanup
// ============================================

chrome.tabs.onRemoved.addListener((tabId) => {
  hiddenCountByTab.delete(tabId);
});
